version: '3.9'
services:
  asir-apache:
    image: php:7.4-apache
    networks:
      bind9_subnet:
        ipv4_address: 10.1.0.225
    container_name: asir-apache
    ports:
    - '80:80'
    - '8000:8000'
    - '443:443'
    volumes:
    - ./html:/var/www/html
    - ./confApache:/etc/apache2

  asir_cliente:
      container_name: asir_cliente2
      image: alpine
      networks:
        bind9_subnet:
          ipv4_address: 10.1.0.224
      stdin_open: true #docker run -i
      tty: true        #docker run -t
      dns:
          - 10.1.0.222

  bind9:
    container_name: asir_bind
    image: internetsystemsconsortium/bind9:9.16
    networks:
      bind9_subnet:
        ipv4_address: 10.1.0.222
    volumes:
       - ~/Escritorio/sri/proyectoApache/config:/etc/bind
       - ~/Escritorio/sri/proyectoApache/zonas:/var/lib/bind

  firefox:
    container_name: firefox
    image: jlesage/firefox
    ports:
    -  '5800:5800'
    volumes:
    - ./firefox:/config:rw
    dns:
    - 10.1.0.222
    networks:
      bind9_subnet:
        ipv4_address: 10.1.0.221

  wireshark:
    image: lscr.io/linuxserver/wireshark:latest
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    security_opt: 
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./wireshark:/config
    ports:
      - '3000:3000'
    restart: unless-stopped


networks:
    bind9_subnet:
        external: true
